// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvGJxdeqwO3n_pI8owDc0uIsIcMFI8nyM',
    appId: '1:44920971197:web:813a204d10a72d6f397cd4',
    messagingSenderId: '44920971197',
    projectId: 'kigali-directory-15b54',
    authDomain: 'kigali-directory-15b54.firebaseapp.com',
    storageBucket: 'kigali-directory-15b54.firebasestorage.app',
    measurementId: 'G-LJSX5MZPHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuHCOFAUnWXSqEPVqNU8PbWvm3Xhk0y6c',
    appId: '1:44920971197:android:11e68681b034109a397cd4',
    messagingSenderId: '44920971197',
    projectId: 'kigali-directory-15b54',
    storageBucket: 'kigali-directory-15b54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn84jJNLplJPkdVckCMVzQVpgdibuLGN8',
    appId: '1:44920971197:ios:fd5e70d8e201dfcb397cd4',
    messagingSenderId: '44920971197',
    projectId: 'kigali-directory-15b54',
    storageBucket: 'kigali-directory-15b54.firebasestorage.app',
    iosBundleId: 'com.example.kigaliDirectory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn84jJNLplJPkdVckCMVzQVpgdibuLGN8',
    appId: '1:44920971197:ios:fd5e70d8e201dfcb397cd4',
    messagingSenderId: '44920971197',
    projectId: 'kigali-directory-15b54',
    storageBucket: 'kigali-directory-15b54.firebasestorage.app',
    iosBundleId: 'com.example.kigaliDirectory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvGJxdeqwO3n_pI8owDc0uIsIcMFI8nyM',
    appId: '1:44920971197:web:bf2113ba96911bb7397cd4',
    messagingSenderId: '44920971197',
    projectId: 'kigali-directory-15b54',
    authDomain: 'kigali-directory-15b54.firebaseapp.com',
    storageBucket: 'kigali-directory-15b54.firebasestorage.app',
    measurementId: 'G-GGVFBRQLEB',
  );
}
